services:
  - type: web
    name: ledo-sports-academy
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    autoDeploy: true
    numInstances: 1
    plan: free 
